blank_issues_enabled: false
contact_links:
  - name: Наш Discord-сервер
    url: https://discord.gg/X8yWNWpTQs
    about: Вопросы по JavaScript, HTML, CSS, Node.js, React, TypeScript, Vue.js, Angular, а также «code review» и обсуждение программирования в целом
