name: 📙 Предложить идею по улучшению материала учебника
description: Предложения о добавлении новых разделов/статей в учебник; о переработке существующих статей; о добавлении новых материалов в статьи
title: "[Предложение: учебник]: "
labels: ["suggestion: tutorial"]
body:
  - type: markdown
    attributes:
      value: |
        ## <ins>Не</ins> открывайте Issue в этой категории, если хотите предложить:
          * Исправление/изменение кода в какой-либо из статей
          * Исправление неточности/устаревшей информации в какой-либо из статей
          * Исправление орфографических/пунктуационных/стилистических ошибок в какой-либо из статей
          * Добавление задач в какую-либо из статей

        ...А так же любые другие **небольшие** правки, которые, на ваш взгляд, не требуют обсуждения и могут быть сразу отправлены на рассмотрение.
          * «[Как внести правки в учебник?](../blob/master/CONTRIBUTING.md#как-внести-правки-в-учебник)»
        ## <ins>Открывайте</ins> Issue в этой категории, если хотите предложить:
          * Переработку какой-либо статьи (или переработку определенной части статьи)
          * Добавление новых разделов в учебник
          * Добавление новых статей в учебник
          * Добавление нового материала в какую-либо из статей
          * ...а так же любые другие **крупные** правки

        Перечисленные выше темы требуют предварительного обсуждения с редакторами учебника.
  - type: textarea
    id: suggestion-description
    attributes:
      label: Описание
      description: Что именно вы хотите предложить? 
      placeholder: |
        Например: «в JavaScript недавно был добавлен [...] — на мой взгляд, было бы неплохо сделать новую статью на эту тему». 
    validations:
      required: true
  - type: textarea
    id: suggestion-motivation
    attributes:
      label: Мотивация
      description: Почему предлагаемые правки действительно должны быть внесены в учебник? 
      placeholder: |
        Например: «я считаю, что любое представление о [...] без понимания концепции [...] будет недостаточным и неполным, у читателя может сложиться ложное впечатление».
    validations:
      required: true
  - type: dropdown
    id: suggestion-question
    attributes:
      label: Готовы ли вы принять участие в реализации данного предложения? 
      description: Например, если вы предлагаете добавить новую статью — готовы ли вы заняться её написанием? 
      options:
        - Да, я готов(а) принять участие.
        - Нет, я не готов(а) принимать участие. Оставляю эту возможность редакторам учебника. 
    validations:
        required: true
