name: 🌐 Предложить идею по улучшению веб-сайта 
description: Предложения о добавлении нового функционала на сайт учебника; ошибки/опечатки во вкладках «Курсы», «Тесты знаний», «Скринкасты», «о проекте» и т.д; идеи по улучшению курсов
title: "[Предложение: веб-сайт]: "
labels: ["suggestion: website"]
body:
  - type: markdown
    attributes:
      value: |
        Всё, что касается именно <ins>**веб-сайта**</ins>, на котором опубликован учебник — [https://learn.javascript.ru](https://learn.javascript.ru).

        В этой категории вы можете:
          * Предложить добавление нового функционала на веб-сайт учебника
          * Сообщить об ошибках/опечатках во вкладках «Курсы», «Тесты знаний», «Скринкасты», «о проекте» и т.д.
          * Предложить идеи по улучшению курсов
  - type: textarea
    id: suggestion-description
    attributes:
      label: Описание
      description: Что именно вы хотите предложить (или о чём хотите сообщить)? 
      placeholder: |
        Например: «мне кажется, было бы неплохо добавить возможность [...]». 
    validations:
      required: true
