name: 📨 Задать вопрос
description: Вопросы по материалу учебника; по веб-сайту; по редактированию учебника
title: "[Вопрос]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Любые вопросы по материалу учебника; по веб-сайту; по редактированию учебника и т.д.

        ### <ins>**Мы не консультируем по вопросам о JavaScript здесь.**</ins> Для этих целей есть [Discord-сервер](https://discord.gg/X8yWNWpTQs). 
  - type: textarea
    id: question-description
    attributes:
      label: Описание
      description: О чём вы хотите спросить?
      placeholder: |
        Например: «почему раздел [...] идёт перед разделом [...], а не после него?». 
    validations:
      required: true
